//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcNotas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bdnotasEntities : DbContext
    {
        public bdnotasEntities()
            : base("name=bdnotasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<especialidad> especialidad { get; set; }
        public virtual DbSet<NOTAS> NOTAS { get; set; }
        public virtual DbSet<PAGOS> PAGOS { get; set; }
    
        public virtual ObjectResult<string> SPADIALU(string aP, string nOM, string eS, string pRO)
        {
            var aPParameter = aP != null ?
                new ObjectParameter("AP", aP) :
                new ObjectParameter("AP", typeof(string));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var eSParameter = eS != null ?
                new ObjectParameter("ES", eS) :
                new ObjectParameter("ES", typeof(string));
    
            var pROParameter = pRO != null ?
                new ObjectParameter("PRO", pRO) :
                new ObjectParameter("PRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SPADIALU", aPParameter, nOMParameter, eSParameter, pROParameter);
        }
    
        public virtual ObjectResult<SPALU_Result> SPALU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPALU_Result>("SPALU");
        }
    
        public virtual int spanula(string cod)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spanula", codParameter);
        }
    
        public virtual int SPcambia(string cod, string aP, string nOM, string eS, string pRO)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            var aPParameter = aP != null ?
                new ObjectParameter("AP", aP) :
                new ObjectParameter("AP", typeof(string));
    
            var nOMParameter = nOM != null ?
                new ObjectParameter("NOM", nOM) :
                new ObjectParameter("NOM", typeof(string));
    
            var eSParameter = eS != null ?
                new ObjectParameter("ES", eS) :
                new ObjectParameter("ES", typeof(string));
    
            var pROParameter = pRO != null ?
                new ObjectParameter("PRO", pRO) :
                new ObjectParameter("PRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPcambia", codParameter, aPParameter, nOMParameter, eSParameter, pROParameter);
        }
    
        public virtual ObjectResult<SPESP_Result> SPESP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPESP_Result>("SPESP");
        }
    
        public virtual ObjectResult<SPLISALU_Result> SPLISALU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPLISALU_Result>("SPLISALU");
        }
    
        public virtual ObjectResult<spmes_Result> spmes(Nullable<int> an)
        {
            var anParameter = an.HasValue ?
                new ObjectParameter("an", an) :
                new ObjectParameter("an", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spmes_Result>("spmes", anParameter);
        }
    
        public virtual ObjectResult<spnota_Result> spnota(string cod)
        {
            var codParameter = cod != null ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spnota_Result>("spnota", codParameter);
        }
    }
}
