//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManteminiemtoClinica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BDCLINICA2Entities : DbContext
    {
        public BDCLINICA2Entities()
            : base("name=BDCLINICA2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Citas> Citas { get; set; }
        public DbSet<Medicos> Medicos { get; set; }
        public DbSet<tabesp> tabesp { get; set; }
    
        public virtual int sp_AdiCita(string codMed, string nomPac, Nullable<int> tipo, Nullable<decimal> costEsp)
        {
            var codMedParameter = codMed != null ?
                new ObjectParameter("codMed", codMed) :
                new ObjectParameter("codMed", typeof(string));
    
            var nomPacParameter = nomPac != null ?
                new ObjectParameter("nomPac", nomPac) :
                new ObjectParameter("nomPac", typeof(string));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            var costEspParameter = costEsp.HasValue ?
                new ObjectParameter("costEsp", costEsp) :
                new ObjectParameter("costEsp", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AdiCita", codMedParameter, nomPacParameter, tipoParameter, costEspParameter);
        }
    }
}
