//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManteminiemtoClinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabesp
    {
        public string code { get; set; }
        public string nome { get; set; }
        public Nullable<decimal> costo { get; set; }
    }
}
