//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Artefacto
{
    public string art_cod { get; set; }
    public string Lin_cod { get; set; }
    public string art_nom { get; set; }
    public Nullable<decimal> art_pre { get; set; }
    public string art_img { get; set; }
}

public partial class Calendario
{
    public string nro_pro { get; set; }
    public int nro_cuota { get; set; }
    public Nullable<decimal> monto { get; set; }
    public Nullable<decimal> saldo { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
}

public partial class Clientes
{
    public string cli_cod { get; set; }
    public string cli_nom { get; set; }
    public Nullable<decimal> cli_tel { get; set; }
    public Nullable<decimal> cli_ruc { get; set; }
    public string cli_dir { get; set; }
}

public partial class Linea
{
    public string Lin_cod { get; set; }
    public string Lin_nom { get; set; }
}

public partial class proforma
{
    public string nro_pro { get; set; }
    public string cli_cod { get; set; }
    public string art_cod { get; set; }
    public Nullable<decimal> precio { get; set; }
    public string tipo_ven { get; set; }
}

public partial class sp_ArtefactosxLinea_Result
{
    public string art_cod { get; set; }
    public string Lin_cod { get; set; }
    public string art_nom { get; set; }
    public Nullable<decimal> art_pre { get; set; }
    public string art_img { get; set; }
}

public partial class sp_ListarProfConFormato_Result
{
    public string nro_pro { get; set; }
    public string cli_cod { get; set; }
    public string art_cod { get; set; }
    public Nullable<decimal> precio { get; set; }
    public Nullable<int> meses { get; set; }
}

public partial class sp_ListarProfConFormato2_Result
{
    public string nro_pro { get; set; }
    public string cli_cod { get; set; }
    public string art_cod { get; set; }
    public Nullable<decimal> precio { get; set; }
    public Nullable<int> meses { get; set; }
    public Nullable<decimal> interes { get; set; }
    public Nullable<decimal> saldo { get; set; }
}
