#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36373
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bdnotas")]
public partial class DataNotasDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAlumno(Alumno instance);
  partial void UpdateAlumno(Alumno instance);
  partial void DeleteAlumno(Alumno instance);
  partial void InsertCurso(Curso instance);
  partial void UpdateCurso(Curso instance);
  partial void DeleteCurso(Curso instance);
  partial void Insertespecialidad(especialidad instance);
  partial void Updateespecialidad(especialidad instance);
  partial void Deleteespecialidad(especialidad instance);
  partial void InsertNOTA(NOTA instance);
  partial void UpdateNOTA(NOTA instance);
  partial void DeleteNOTA(NOTA instance);
  partial void InsertPAGO(PAGO instance);
  partial void UpdatePAGO(PAGO instance);
  partial void DeletePAGO(PAGO instance);
  #endregion
	
	public DataNotasDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bdnotasConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataNotasDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataNotasDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataNotasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataNotasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Alumno> Alumnos
	{
		get
		{
			return this.GetTable<Alumno>();
		}
	}
	
	public System.Data.Linq.Table<Curso> Cursos
	{
		get
		{
			return this.GetTable<Curso>();
		}
	}
	
	public System.Data.Linq.Table<especialidad> especialidads
	{
		get
		{
			return this.GetTable<especialidad>();
		}
	}
	
	public System.Data.Linq.Table<NOTA> NOTAs
	{
		get
		{
			return this.GetTable<NOTA>();
		}
	}
	
	public System.Data.Linq.Table<PAGO> PAGOs
	{
		get
		{
			return this.GetTable<PAGO>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spnota")]
	public ISingleResult<spnotaResult> spnota([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string cod)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod);
		return ((ISingleResult<spnotaResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spadiAlu")]
	public int spadiAlu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string ape, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(3)")] string es, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> pro)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ape, nom, es, pro);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spDelAlu")]
	public int spDelAlu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string coda)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), coda);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spmodiAlu")]
	public int spmodiAlu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(5)")] string cod, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string ape, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string nom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(3)")] string es, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> pro)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cod, ape, nom, es, pro);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdAlumno;
	
	private string _ApeAlumno;
	
	private string _NomAlumno;
	
	private string _Idesp;
	
	private System.Nullable<char> _proce;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAlumnoChanging(string value);
    partial void OnIdAlumnoChanged();
    partial void OnApeAlumnoChanging(string value);
    partial void OnApeAlumnoChanged();
    partial void OnNomAlumnoChanging(string value);
    partial void OnNomAlumnoChanged();
    partial void OnIdespChanging(string value);
    partial void OnIdespChanged();
    partial void OnproceChanging(System.Nullable<char> value);
    partial void OnproceChanged();
    #endregion
	
	public Alumno()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlumno", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdAlumno
	{
		get
		{
			return this._IdAlumno;
		}
		set
		{
			if ((this._IdAlumno != value))
			{
				this.OnIdAlumnoChanging(value);
				this.SendPropertyChanging();
				this._IdAlumno = value;
				this.SendPropertyChanged("IdAlumno");
				this.OnIdAlumnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApeAlumno", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string ApeAlumno
	{
		get
		{
			return this._ApeAlumno;
		}
		set
		{
			if ((this._ApeAlumno != value))
			{
				this.OnApeAlumnoChanging(value);
				this.SendPropertyChanging();
				this._ApeAlumno = value;
				this.SendPropertyChanged("ApeAlumno");
				this.OnApeAlumnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomAlumno", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string NomAlumno
	{
		get
		{
			return this._NomAlumno;
		}
		set
		{
			if ((this._NomAlumno != value))
			{
				this.OnNomAlumnoChanging(value);
				this.SendPropertyChanging();
				this._NomAlumno = value;
				this.SendPropertyChanged("NomAlumno");
				this.OnNomAlumnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idesp", DbType="Char(3) NOT NULL", CanBeNull=false)]
	public string Idesp
	{
		get
		{
			return this._Idesp;
		}
		set
		{
			if ((this._Idesp != value))
			{
				this.OnIdespChanging(value);
				this.SendPropertyChanging();
				this._Idesp = value;
				this.SendPropertyChanged("Idesp");
				this.OnIdespChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proce", DbType="Char(1)")]
	public System.Nullable<char> proce
	{
		get
		{
			return this._proce;
		}
		set
		{
			if ((this._proce != value))
			{
				this.OnproceChanging(value);
				this.SendPropertyChanging();
				this._proce = value;
				this.SendPropertyChanged("proce");
				this.OnproceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Curso")]
public partial class Curso : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdCurso;
	
	private string _NomCurso;
	
	private System.Nullable<int> _credito;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCursoChanging(string value);
    partial void OnIdCursoChanged();
    partial void OnNomCursoChanging(string value);
    partial void OnNomCursoChanged();
    partial void OncreditoChanging(System.Nullable<int> value);
    partial void OncreditoChanged();
    #endregion
	
	public Curso()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdCurso
	{
		get
		{
			return this._IdCurso;
		}
		set
		{
			if ((this._IdCurso != value))
			{
				this.OnIdCursoChanging(value);
				this.SendPropertyChanging();
				this._IdCurso = value;
				this.SendPropertyChanged("IdCurso");
				this.OnIdCursoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomCurso", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
	public string NomCurso
	{
		get
		{
			return this._NomCurso;
		}
		set
		{
			if ((this._NomCurso != value))
			{
				this.OnNomCursoChanging(value);
				this.SendPropertyChanging();
				this._NomCurso = value;
				this.SendPropertyChanged("NomCurso");
				this.OnNomCursoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_credito", DbType="Int")]
	public System.Nullable<int> credito
	{
		get
		{
			return this._credito;
		}
		set
		{
			if ((this._credito != value))
			{
				this.OncreditoChanging(value);
				this.SendPropertyChanging();
				this._credito = value;
				this.SendPropertyChanged("credito");
				this.OncreditoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.especialidad")]
public partial class especialidad : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Idesp;
	
	private string _Nomesp;
	
	private decimal _costo;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdespChanging(string value);
    partial void OnIdespChanged();
    partial void OnNomespChanging(string value);
    partial void OnNomespChanged();
    partial void OncostoChanging(decimal value);
    partial void OncostoChanged();
    #endregion
	
	public especialidad()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idesp", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Idesp
	{
		get
		{
			return this._Idesp;
		}
		set
		{
			if ((this._Idesp != value))
			{
				this.OnIdespChanging(value);
				this.SendPropertyChanging();
				this._Idesp = value;
				this.SendPropertyChanged("Idesp");
				this.OnIdespChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nomesp", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string Nomesp
	{
		get
		{
			return this._Nomesp;
		}
		set
		{
			if ((this._Nomesp != value))
			{
				this.OnNomespChanging(value);
				this.SendPropertyChanging();
				this._Nomesp = value;
				this.SendPropertyChanged("Nomesp");
				this.OnNomespChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Decimal(8,1) NOT NULL")]
	public decimal costo
	{
		get
		{
			return this._costo;
		}
		set
		{
			if ((this._costo != value))
			{
				this.OncostoChanging(value);
				this.SendPropertyChanging();
				this._costo = value;
				this.SendPropertyChanged("costo");
				this.OncostoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOTAS")]
public partial class NOTA : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdAlumno;
	
	private string _IdCurso;
	
	private System.Nullable<float> _ExaParcial;
	
	private System.Nullable<float> _ExaFinal;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAlumnoChanging(string value);
    partial void OnIdAlumnoChanged();
    partial void OnIdCursoChanging(string value);
    partial void OnIdCursoChanged();
    partial void OnExaParcialChanging(System.Nullable<float> value);
    partial void OnExaParcialChanged();
    partial void OnExaFinalChanging(System.Nullable<float> value);
    partial void OnExaFinalChanged();
    #endregion
	
	public NOTA()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlumno", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdAlumno
	{
		get
		{
			return this._IdAlumno;
		}
		set
		{
			if ((this._IdAlumno != value))
			{
				this.OnIdAlumnoChanging(value);
				this.SendPropertyChanging();
				this._IdAlumno = value;
				this.SendPropertyChanged("IdAlumno");
				this.OnIdAlumnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCurso", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdCurso
	{
		get
		{
			return this._IdCurso;
		}
		set
		{
			if ((this._IdCurso != value))
			{
				this.OnIdCursoChanging(value);
				this.SendPropertyChanging();
				this._IdCurso = value;
				this.SendPropertyChanged("IdCurso");
				this.OnIdCursoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaParcial", DbType="Real")]
	public System.Nullable<float> ExaParcial
	{
		get
		{
			return this._ExaParcial;
		}
		set
		{
			if ((this._ExaParcial != value))
			{
				this.OnExaParcialChanging(value);
				this.SendPropertyChanging();
				this._ExaParcial = value;
				this.SendPropertyChanged("ExaParcial");
				this.OnExaParcialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExaFinal", DbType="Real")]
	public System.Nullable<float> ExaFinal
	{
		get
		{
			return this._ExaFinal;
		}
		set
		{
			if ((this._ExaFinal != value))
			{
				this.OnExaFinalChanging(value);
				this.SendPropertyChanging();
				this._ExaFinal = value;
				this.SendPropertyChanged("ExaFinal");
				this.OnExaFinalChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAGOS")]
public partial class PAGO : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _IdAlumno;
	
	private string _Ciclo;
	
	private int _nCuota;
	
	private decimal _Monto;
	
	private System.Nullable<System.DateTime> _Fecha;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAlumnoChanging(string value);
    partial void OnIdAlumnoChanged();
    partial void OnCicloChanging(string value);
    partial void OnCicloChanged();
    partial void OnnCuotaChanging(int value);
    partial void OnnCuotaChanged();
    partial void OnMontoChanging(decimal value);
    partial void OnMontoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
	
	public PAGO()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlumno", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string IdAlumno
	{
		get
		{
			return this._IdAlumno;
		}
		set
		{
			if ((this._IdAlumno != value))
			{
				this.OnIdAlumnoChanging(value);
				this.SendPropertyChanging();
				this._IdAlumno = value;
				this.SendPropertyChanged("IdAlumno");
				this.OnIdAlumnoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ciclo", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Ciclo
	{
		get
		{
			return this._Ciclo;
		}
		set
		{
			if ((this._Ciclo != value))
			{
				this.OnCicloChanging(value);
				this.SendPropertyChanging();
				this._Ciclo = value;
				this.SendPropertyChanged("Ciclo");
				this.OnCicloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nCuota", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int nCuota
	{
		get
		{
			return this._nCuota;
		}
		set
		{
			if ((this._nCuota != value))
			{
				this.OnnCuotaChanging(value);
				this.SendPropertyChanging();
				this._nCuota = value;
				this.SendPropertyChanged("nCuota");
				this.OnnCuotaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(12,2) NOT NULL")]
	public decimal Monto
	{
		get
		{
			return this._Monto;
		}
		set
		{
			if ((this._Monto != value))
			{
				this.OnMontoChanging(value);
				this.SendPropertyChanging();
				this._Monto = value;
				this.SendPropertyChanged("Monto");
				this.OnMontoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
	public System.Nullable<System.DateTime> Fecha
	{
		get
		{
			return this._Fecha;
		}
		set
		{
			if ((this._Fecha != value))
			{
				this.OnFechaChanging(value);
				this.SendPropertyChanging();
				this._Fecha = value;
				this.SendPropertyChanged("Fecha");
				this.OnFechaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class spnotaResult
{
	
	private string _idcurso;
	
	private string _nomcurso;
	
	private System.Nullable<float> _exaparcial;
	
	private System.Nullable<float> _exafinal;
	
	private System.Nullable<float> _prom;
	
	private string _obser;
	
	public spnotaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idcurso", DbType="Char(4) NOT NULL", CanBeNull=false)]
	public string idcurso
	{
		get
		{
			return this._idcurso;
		}
		set
		{
			if ((this._idcurso != value))
			{
				this._idcurso = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomcurso", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
	public string nomcurso
	{
		get
		{
			return this._nomcurso;
		}
		set
		{
			if ((this._nomcurso != value))
			{
				this._nomcurso = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exaparcial", DbType="Real")]
	public System.Nullable<float> exaparcial
	{
		get
		{
			return this._exaparcial;
		}
		set
		{
			if ((this._exaparcial != value))
			{
				this._exaparcial = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exafinal", DbType="Real")]
	public System.Nullable<float> exafinal
	{
		get
		{
			return this._exafinal;
		}
		set
		{
			if ((this._exafinal != value))
			{
				this._exafinal = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prom", DbType="Real")]
	public System.Nullable<float> prom
	{
		get
		{
			return this._prom;
		}
		set
		{
			if ((this._prom != value))
			{
				this._prom = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_obser", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
	public string obser
	{
		get
		{
			return this._obser;
		}
		set
		{
			if ((this._obser != value))
			{
				this._obser = value;
			}
		}
	}
}
#pragma warning restore 1591
