//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;  //Importamos la clase de anotaciones para hacer VALIDACIONES


namespace MantenimientoMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.NOTAS = new HashSet<NOTAS>();
            this.PAGOS = new HashSet<PAGOS>();
        }
    
        public string IdAlumno { get; set; }
        [Required(ErrorMessage = "Dato Obligatorio")]
        [RegularExpression("[A-Za-z ñÑ]+$", ErrorMessage = "Solo letras o espacios")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Longitud mínima 2 caracteres")]
        public string ApeAlumno { get; set; }
        [Required(ErrorMessage = "Dato Obligatorio")]
        [RegularExpression("[A-Za-z ñÑ]+$", ErrorMessage = "Solo letras o espacios")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Longitud mínima 2 caracteres")]
        public string NomAlumno { get; set; }
        public string Idesp { get; set; }
        public string proce { get; set; }
    
        public virtual especialidad especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS> NOTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGOS> PAGOS { get; set; }
    }
}
